// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.ToolCategory;

privileged aspect ToolCategory_Roo_JavaBean {
    
    public String ToolCategory.getName() {
        return this.name;
    }
    
    public void ToolCategory.setName(String name) {
        this.name = name;
    }
    
}
