INSERT INTO "APP"."USER_ROLE" (ID,NAME,VERSION) VALUES (1221,'LEADER',0);
INSERT INTO "APP"."USER_ROLE" (ID,NAME,VERSION) VALUES (1222,'ASSISTANT',0);
INSERT INTO "APP"."USER_ROLE" (ID,NAME,VERSION) VALUES (1223,'RESEARCHER',0);
INSERT INTO "APP"."USER_ROLE" (ID,NAME,VERSION) VALUES (1225,'USER_ROLE',0);
INSERT INTO "APP"."USER_ROLE" (ID,NAME,VERSION) VALUES (1226,'ADMIN_ROLE',0);
