INSERT INTO "APP"."INSTITUTION" (ID,NAME,VERSION) VALUES (0,'UNKNOWN',0);
INSERT INTO "APP"."INSTITUTION" (ID,NAME,VERSION) VALUES (1,'Deakin University',0);
INSERT INTO "APP"."INSTITUTION" (ID,NAME,VERSION) VALUES (2,'Monash University',0);
INSERT INTO "APP"."INSTITUTION" (ID,NAME,VERSION) VALUES (3,'RMIT University of Technology',0);
INSERT INTO "APP"."INSTITUTION" (ID,NAME,VERSION) VALUES (4,'University of Melbourne',0);
