// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.Researcher;
import au.net.huni.model.ResearcherDataOnDemand;

privileged aspect ResearcherDataOnDemand_Roo_DataOnDemand {
    
    public void ResearcherDataOnDemand.setIsAccountEnabled(Researcher obj, int index) {
        Boolean isAccountEnabled = Boolean.TRUE;
        obj.setIsAccountEnabled(isAccountEnabled);
    }
    
    public void ResearcherDataOnDemand.setPassword(Researcher obj, int index) {
        String password = "passwordxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_" + index;
        if (password.length() > 64) {
            password = password.substring(0, 64);
        }
        obj.setPassword(password);
    }
    
}
