CREATE TABLE "APP"."TOOL_PARAMETER"(
ID BIGINT PRIMARY KEY not null,
AMOUNT VARCHAR(64),
DISPLAY_ORDER INTEGER not null,
NAME VARCHAR(64) not null,
VERSION INTEGER,
OWNER BIGINT not null,
FOREIGN KEY (OWNER) REFERENCES HISTORY_ITEM(ID))
