CREATE TABLE "APP"."TOOL_CATALOG_ITEM_CATEGORIES"(
TOOL_CATALOG_ITEM BIGINT not null,
CATEGORIES BIGINT not null,
FOREIGN KEY (TOOL_CATALOG_ITEM) REFERENCES TOOL_CATALOG_ITEM(ID),
FOREIGN KEY (CATEGORIES) REFERENCES TOOL_CATEGORY(ID))
