CREATE TABLE "APP"."RESEARCHER"(
ID BIGINT PRIMARY KEY default 'GENERATED_BY_DEFAULT' not null,
CREATION_DATE TIMESTAMP not null,
EMAIL_ADDRESS VARCHAR not null,
FAMILY_NAME VARCHAR not null,
GIVEN_NAME VARCHAR not null,
IS_ACCOUNT_ENABLED SMALLINT,
PASSWORD VARCHAR,
USER_NAME VARCHAR not null,
VERSION INTEGER,
INSTITUTION BIGINT not null,
FOREIGN KEY (INSTITUTION) REFERENCES INSTITUTION(ID))
