CREATE TABLE "APP"."RESEARCHER"(
ID BIGINT PRIMARY KEY not null,
CREATION_DATE TIMESTAMP not null,
EMAIL_ADDRESS VARCHAR(64) not null,
FAMILY_NAME VARCHAR(64) not null,
GIVEN_NAME VARCHAR(64) not null,
IS_ACCOUNT_ENABLED SMALLINT,
PASSWORD VARCHAR(64),
USER_NAME VARCHAR(64) not null,
VERSION INTEGER,
DEFAULT_TOOL BIGINT not null,
INSTITUTION BIGINT not null,
FOREIGN KEY (INSTITUTION) REFERENCES INSTITUTION(ID),
FOREIGN KEY (DEFAULT_TOOL) REFERENCES TOOL_CATALOG_ITEM(ID))
