CREATE TABLE "APP"."RESEARCHER_TOOLKIT"(
RESEARCHER BIGINT not null,
TOOLKIT BIGINT not null,
FOREIGN KEY (RESEARCHER) REFERENCES RESEARCHER(ID),
FOREIGN KEY (TOOLKIT) REFERENCES TOOL_CATALOG_ITEM(ID))
