CREATE TABLE "APP"."TOOL_PARAMETER"(
ID BIGINT PRIMARY KEY default 'GENERATED_BY_DEFAULT' not null,
AMOUNT VARCHAR,
DISPLAY_ORDER INTEGER not null,
NAME VARCHAR not null,
VERSION INTEGER,
OWNER BIGINT not null,
FOREIGN KEY (OWNER) REFERENCES HISTORY_ITEM(ID))
