CREATE TABLE "APP"."REGISTRATION"(
ID BIGINT PRIMARY KEY not null,
APPLICATION_DATE TIMESTAMP not null,
APPROVAL_DATE TIMESTAMP,
EMAIL_ADDRESS VARCHAR(64) not null,
FAMILY_NAME VARCHAR(64) not null,
GIVEN_NAME VARCHAR(64) not null,
STATUS INTEGER not null,
USER_NAME VARCHAR(32) not null,
VERSION INTEGER,
INSTITUTION BIGINT not null,
FOREIGN KEY (INSTITUTION) REFERENCES INSTITUTION(ID))
