// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.tool_library.model;

import au.net.huni.tool_library.model.Tool;
import au.net.huni.tool_library.model.ToolDataOnDemand;
import au.net.huni.tool_library.model.ToolIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ToolIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ToolIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ToolIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ToolIntegrationTest: @Transactional;
    
    @Autowired
    ToolDataOnDemand ToolIntegrationTest.dod;
    
    @Test
    public void ToolIntegrationTest.testCountTools() {
        Assert.assertNotNull("Data on demand for 'Tool' failed to initialize correctly", dod.getRandomTool());
        long count = Tool.countTools();
        Assert.assertTrue("Counter for 'Tool' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ToolIntegrationTest.testFindTool() {
        Tool obj = dod.getRandomTool();
        Assert.assertNotNull("Data on demand for 'Tool' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tool' failed to provide an identifier", id);
        obj = Tool.findTool(id);
        Assert.assertNotNull("Find method for 'Tool' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tool' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ToolIntegrationTest.testFindAllTools() {
        Assert.assertNotNull("Data on demand for 'Tool' failed to initialize correctly", dod.getRandomTool());
        long count = Tool.countTools();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tool', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tool> result = Tool.findAllTools();
        Assert.assertNotNull("Find all method for 'Tool' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tool' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ToolIntegrationTest.testFindToolEntries() {
        Assert.assertNotNull("Data on demand for 'Tool' failed to initialize correctly", dod.getRandomTool());
        long count = Tool.countTools();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tool> result = Tool.findToolEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tool' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tool' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ToolIntegrationTest.testFlush() {
        Tool obj = dod.getRandomTool();
        Assert.assertNotNull("Data on demand for 'Tool' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tool' failed to provide an identifier", id);
        obj = Tool.findTool(id);
        Assert.assertNotNull("Find method for 'Tool' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTool(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Tool' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ToolIntegrationTest.testMergeUpdate() {
        Tool obj = dod.getRandomTool();
        Assert.assertNotNull("Data on demand for 'Tool' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tool' failed to provide an identifier", id);
        obj = Tool.findTool(id);
        boolean modified =  dod.modifyTool(obj);
        Integer currentVersion = obj.getVersion();
        Tool merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tool' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ToolIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Tool' failed to initialize correctly", dod.getRandomTool());
        Tool obj = dod.getNewTransientTool(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tool' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tool' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Tool' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ToolIntegrationTest.testRemove() {
        Tool obj = dod.getRandomTool();
        Assert.assertNotNull("Data on demand for 'Tool' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tool' failed to provide an identifier", id);
        obj = Tool.findTool(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Tool' with identifier '" + id + "'", Tool.findTool(id));
    }
    
}
