// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.tool_library.model;

import au.net.huni.tool_library.model.ToolDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ToolDataOnDemand_Roo_Configurable {
    
    declare @type: ToolDataOnDemand: @Configurable;
    
}
