CREATE TABLE "APP"."FEEDBACK_ITEM"(
ID BIGINT PRIMARY KEY not null,
COMMENT VARCHAR(255),
CONTEXT VARCHAR(64),
FEEDBACK_DATE TIMESTAMP not null,
RATING INTEGER,
VERSION INTEGER,
VISITOR_IP_ADDRESS VARCHAR(255))
