CREATE TABLE "APP"."HISTORY_ITEM"(
ID BIGINT PRIMARY KEY default 'GENERATED_BY_DEFAULT' not null,
BACKGROUND_COLOUR VARCHAR not null,
EXECUTION_DATE TIMESTAMP not null,
TOOL_NAME VARCHAR not null,
VERSION INTEGER,
OWNER BIGINT not null,
FOREIGN KEY (OWNER) REFERENCES RESEARCHER(ID))
