CREATE TABLE "APP"."HISTORY_ITEM"(
ID BIGINT PRIMARY KEY not null,
BACKGROUND_COLOUR VARCHAR(32) not null,
EXECUTION_DATE TIMESTAMP not null,
TOOL_NAME VARCHAR(64) not null,
VERSION INTEGER,
OWNER BIGINT not null,
FOREIGN KEY (OWNER) REFERENCES RESEARCHER(ID))
