// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.Institution;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Institution_Roo_Configurable {
    
    declare @type: Institution: @Configurable;
    
}
