// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.springframework.stereotype.Component;

privileged aspect DataSourceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DataSourceDataOnDemand: @Component;
    
    private Random DataSourceDataOnDemand.rnd = new SecureRandom();
    
    private List<DataSource> DataSourceDataOnDemand.data;
    
    public void DataSourceDataOnDemand.setDescription(DataSource obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void DataSourceDataOnDemand.setImportDate(DataSource obj, int index) {
        Calendar importDate = Calendar.getInstance();
        obj.setImportDate(importDate);
    }
    
    public void DataSourceDataOnDemand.setName(DataSource obj, int index) {
        String name = "name_" + index;
        if (name.length() > 64) {
            name = new Random().nextInt(10) + name.substring(1, 64);
        }
        obj.setName(name);
    }
    
    public DataSource DataSourceDataOnDemand.getSpecificDataSource(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DataSource obj = data.get(index);
        Long id = obj.getId();
        return DataSource.findDataSource(id);
    }
    
    public DataSource DataSourceDataOnDemand.getRandomDataSource() {
        init();
        DataSource obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DataSource.findDataSource(id);
    }
    
    public boolean DataSourceDataOnDemand.modifyDataSource(DataSource obj) {
        return false;
    }
    
    public void DataSourceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DataSource.findDataSourceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DataSource' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DataSource>();
        for (int i = 0; i < 10; i++) {
            DataSource obj = getNewTransientDataSource(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
