// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.FeedbackItem;
import au.net.huni.model.FeedbackItemDataOnDemand;
import au.net.huni.model.Rating;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect FeedbackItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FeedbackItemDataOnDemand: @Component;
    
    private Random FeedbackItemDataOnDemand.rnd = new SecureRandom();
    
    private List<FeedbackItem> FeedbackItemDataOnDemand.data;
    
    public FeedbackItem FeedbackItemDataOnDemand.getNewTransientFeedbackItem(int index) {
        FeedbackItem obj = new FeedbackItem();
        setComment(obj, index);
        setContext(obj, index);
        setRating(obj, index);
        return obj;
    }
    
    public void FeedbackItemDataOnDemand.setComment(FeedbackItem obj, int index) {
        String comment = "comment_" + index;
        obj.setComment(comment);
    }
    
    public void FeedbackItemDataOnDemand.setContext(FeedbackItem obj, int index) {
        String context = "context_" + index;
        obj.setContext(context);
    }
    
    public void FeedbackItemDataOnDemand.setRating(FeedbackItem obj, int index) {
        Rating rating = Rating.class.getEnumConstants()[0];
        obj.setRating(rating);
    }
    
    public FeedbackItem FeedbackItemDataOnDemand.getSpecificFeedbackItem(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FeedbackItem obj = data.get(index);
        Long id = obj.getId();
        return FeedbackItem.findFeedbackItem(id);
    }
    
    public FeedbackItem FeedbackItemDataOnDemand.getRandomFeedbackItem() {
        init();
        FeedbackItem obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return FeedbackItem.findFeedbackItem(id);
    }
    
    public boolean FeedbackItemDataOnDemand.modifyFeedbackItem(FeedbackItem obj) {
        return false;
    }
    
    public void FeedbackItemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = FeedbackItem.findFeedbackItemEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FeedbackItem' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FeedbackItem>();
        for (int i = 0; i < 10; i++) {
            FeedbackItem obj = getNewTransientFeedbackItem(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
