// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.HistoryItem;
import au.net.huni.model.HistoryItemDataOnDemand;
import au.net.huni.model.HistoryItemIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HistoryItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HistoryItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HistoryItemIntegrationTest: @Transactional;
    
    @Autowired
    HistoryItemDataOnDemand HistoryItemIntegrationTest.dod;
    
    @Test
    public void HistoryItemIntegrationTest.testCountHistoryItems() {
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to initialize correctly", dod.getRandomHistoryItem());
        long count = HistoryItem.countHistoryItems();
        Assert.assertTrue("Counter for 'HistoryItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HistoryItemIntegrationTest.testFindHistoryItem() {
        HistoryItem obj = dod.getRandomHistoryItem();
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to provide an identifier", id);
        obj = HistoryItem.findHistoryItem(id);
        Assert.assertNotNull("Find method for 'HistoryItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HistoryItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HistoryItemIntegrationTest.testFindAllHistoryItems() {
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to initialize correctly", dod.getRandomHistoryItem());
        long count = HistoryItem.countHistoryItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'HistoryItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HistoryItem> result = HistoryItem.findAllHistoryItems();
        Assert.assertNotNull("Find all method for 'HistoryItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HistoryItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HistoryItemIntegrationTest.testFindHistoryItemEntries() {
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to initialize correctly", dod.getRandomHistoryItem());
        long count = HistoryItem.countHistoryItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HistoryItem> result = HistoryItem.findHistoryItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HistoryItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HistoryItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HistoryItemIntegrationTest.testFlush() {
        HistoryItem obj = dod.getRandomHistoryItem();
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to provide an identifier", id);
        obj = HistoryItem.findHistoryItem(id);
        Assert.assertNotNull("Find method for 'HistoryItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHistoryItem(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'HistoryItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HistoryItemIntegrationTest.testMergeUpdate() {
        HistoryItem obj = dod.getRandomHistoryItem();
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to provide an identifier", id);
        obj = HistoryItem.findHistoryItem(id);
        boolean modified =  dod.modifyHistoryItem(obj);
        Integer currentVersion = obj.getVersion();
        HistoryItem merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'HistoryItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HistoryItemIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to initialize correctly", dod.getRandomHistoryItem());
        HistoryItem obj = dod.getNewTransientHistoryItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HistoryItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'HistoryItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HistoryItemIntegrationTest.testRemove() {
        HistoryItem obj = dod.getRandomHistoryItem();
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoryItem' failed to provide an identifier", id);
        obj = HistoryItem.findHistoryItem(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HistoryItem' with identifier '" + id + "'", HistoryItem.findHistoryItem(id));
    }
    
}
