// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.ProjectIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProjectIntegrationTest_Roo_Configurable {
    
    declare @type: ProjectIntegrationTest: @Configurable;
    
}
