// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.Registration;
import au.net.huni.model.RegistrationDataOnDemand;
import au.net.huni.model.RegistrationStatus;
import java.util.Calendar;
import java.util.GregorianCalendar;

privileged aspect RegistrationDataOnDemand_Roo_DataOnDemand {
    
    public void RegistrationDataOnDemand.setStatus(Registration obj, int index) {
        RegistrationStatus status = RegistrationStatus.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
}
