// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.ToolCatalogItem;
import au.net.huni.model.ToolCatalogItemDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ToolCatalogItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ToolCatalogItemDataOnDemand: @Component;
    
    private Random ToolCatalogItemDataOnDemand.rnd = new SecureRandom();
    
    private List<ToolCatalogItem> ToolCatalogItemDataOnDemand.data;
    
    public void ToolCatalogItemDataOnDemand.setDescription(ToolCatalogItem obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void ToolCatalogItemDataOnDemand.setName(ToolCatalogItem obj, int index) {
        String name = "name_" + index;
        if (name.length() > 64) {
            name = new Random().nextInt(10) + name.substring(1, 64);
        }
        obj.setName(name);
    }
    
    public ToolCatalogItem ToolCatalogItemDataOnDemand.getSpecificToolCatalogItem(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ToolCatalogItem obj = data.get(index);
        Long id = obj.getId();
        return ToolCatalogItem.findToolCatalogItem(id);
    }
    
    public ToolCatalogItem ToolCatalogItemDataOnDemand.getRandomToolCatalogItem() {
        init();
        ToolCatalogItem obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ToolCatalogItem.findToolCatalogItem(id);
    }
    
    public boolean ToolCatalogItemDataOnDemand.modifyToolCatalogItem(ToolCatalogItem obj) {
        return false;
    }
    
    public void ToolCatalogItemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ToolCatalogItem.findToolCatalogItemEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ToolCatalogItem' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ToolCatalogItem>();
        for (int i = 0; i < 10; i++) {
            ToolCatalogItem obj = getNewTransientToolCatalogItem(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
