// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.ToolLibraryItemDataOnDemand;
import au.net.huni.model.ToolLibraryItem;
import au.net.huni.model.ToolLibraryItemIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ToolLibraryItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ToolLibraryItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ToolLibraryItemIntegrationTest: @Transactional;
    
    @Autowired
    ToolLibraryItemDataOnDemand ToolLibraryItemIntegrationTest.dod;
    
    @Test
    public void ToolLibraryItemIntegrationTest.testCountToolLibraryItems() {
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to initialize correctly", dod.getRandomToolLibraryItem());
        long count = ToolLibraryItem.countToolLibraryItems();
        Assert.assertTrue("Counter for 'ToolLibraryItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ToolLibraryItemIntegrationTest.testFindToolLibraryItem() {
        ToolLibraryItem obj = dod.getRandomToolLibraryItem();
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to provide an identifier", id);
        obj = ToolLibraryItem.findToolLibraryItem(id);
        Assert.assertNotNull("Find method for 'ToolLibraryItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ToolLibraryItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ToolLibraryItemIntegrationTest.testFindAllToolLibraryItems() {
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to initialize correctly", dod.getRandomToolLibraryItem());
        long count = ToolLibraryItem.countToolLibraryItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'ToolLibraryItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ToolLibraryItem> result = ToolLibraryItem.findAllToolLibraryItems();
        Assert.assertNotNull("Find all method for 'ToolLibraryItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ToolLibraryItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ToolLibraryItemIntegrationTest.testFindToolLibraryItemEntries() {
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to initialize correctly", dod.getRandomToolLibraryItem());
        long count = ToolLibraryItem.countToolLibraryItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ToolLibraryItem> result = ToolLibraryItem.findToolLibraryItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ToolLibraryItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ToolLibraryItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ToolLibraryItemIntegrationTest.testFlush() {
        ToolLibraryItem obj = dod.getRandomToolLibraryItem();
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to provide an identifier", id);
        obj = ToolLibraryItem.findToolLibraryItem(id);
        Assert.assertNotNull("Find method for 'ToolLibraryItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyToolLibraryItem(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ToolLibraryItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ToolLibraryItemIntegrationTest.testMergeUpdate() {
        ToolLibraryItem obj = dod.getRandomToolLibraryItem();
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to provide an identifier", id);
        obj = ToolLibraryItem.findToolLibraryItem(id);
        boolean modified =  dod.modifyToolLibraryItem(obj);
        Integer currentVersion = obj.getVersion();
        ToolLibraryItem merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ToolLibraryItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ToolLibraryItemIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to initialize correctly", dod.getRandomToolLibraryItem());
        ToolLibraryItem obj = dod.getNewTransientToolLibraryItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ToolLibraryItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ToolLibraryItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ToolLibraryItemIntegrationTest.testRemove() {
        ToolLibraryItem obj = dod.getRandomToolLibraryItem();
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ToolLibraryItem' failed to provide an identifier", id);
        obj = ToolLibraryItem.findToolLibraryItem(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ToolLibraryItem' with identifier '" + id + "'", ToolLibraryItem.findToolLibraryItem(id));
    }
    
}
