// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.FeedbackItem;
import au.net.huni.model.FeedbackItemDataOnDemand;
import au.net.huni.model.FeedbackItemIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FeedbackItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FeedbackItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FeedbackItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FeedbackItemIntegrationTest: @Transactional;
    
    @Autowired
    FeedbackItemDataOnDemand FeedbackItemIntegrationTest.dod;
    
    @Test
    public void FeedbackItemIntegrationTest.testCountFeedbackItems() {
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to initialize correctly", dod.getRandomFeedbackItem());
        long count = FeedbackItem.countFeedbackItems();
        Assert.assertTrue("Counter for 'FeedbackItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FeedbackItemIntegrationTest.testFindFeedbackItem() {
        FeedbackItem obj = dod.getRandomFeedbackItem();
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to provide an identifier", id);
        obj = FeedbackItem.findFeedbackItem(id);
        Assert.assertNotNull("Find method for 'FeedbackItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FeedbackItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FeedbackItemIntegrationTest.testFindAllFeedbackItems() {
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to initialize correctly", dod.getRandomFeedbackItem());
        long count = FeedbackItem.countFeedbackItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'FeedbackItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FeedbackItem> result = FeedbackItem.findAllFeedbackItems();
        Assert.assertNotNull("Find all method for 'FeedbackItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FeedbackItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FeedbackItemIntegrationTest.testFindFeedbackItemEntries() {
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to initialize correctly", dod.getRandomFeedbackItem());
        long count = FeedbackItem.countFeedbackItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FeedbackItem> result = FeedbackItem.findFeedbackItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FeedbackItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FeedbackItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FeedbackItemIntegrationTest.testFlush() {
        FeedbackItem obj = dod.getRandomFeedbackItem();
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to provide an identifier", id);
        obj = FeedbackItem.findFeedbackItem(id);
        Assert.assertNotNull("Find method for 'FeedbackItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFeedbackItem(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FeedbackItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FeedbackItemIntegrationTest.testMergeUpdate() {
        FeedbackItem obj = dod.getRandomFeedbackItem();
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to provide an identifier", id);
        obj = FeedbackItem.findFeedbackItem(id);
        boolean modified =  dod.modifyFeedbackItem(obj);
        Integer currentVersion = obj.getVersion();
        FeedbackItem merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FeedbackItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FeedbackItemIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to initialize correctly", dod.getRandomFeedbackItem());
        FeedbackItem obj = dod.getNewTransientFeedbackItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FeedbackItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'FeedbackItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FeedbackItemIntegrationTest.testRemove() {
        FeedbackItem obj = dod.getRandomFeedbackItem();
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FeedbackItem' failed to provide an identifier", id);
        obj = FeedbackItem.findFeedbackItem(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FeedbackItem' with identifier '" + id + "'", FeedbackItem.findFeedbackItem(id));
    }
    
}
