// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.FeedbackItem;
import au.net.huni.model.FeedbackItemDataOnDemand;
import au.net.huni.model.Rating;
import java.util.Calendar;
import java.util.GregorianCalendar;

privileged aspect FeedbackItemDataOnDemand_Roo_DataOnDemand {
    
    public void FeedbackItemDataOnDemand.setFeedbackDate(FeedbackItem obj, int index) {
        Calendar feedbackDate = Calendar.getInstance();
        obj.setFeedbackDate(feedbackDate);
    }
    
    public void FeedbackItemDataOnDemand.setVisitorIpAddress(FeedbackItem obj, int index) {
        String visitorIpAddress = "visitorIpAddress_" + index;
        obj.setVisitorIpAddress(visitorIpAddress);
    }
    
}
