// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ResearcherDataOnDemand_Roo_Configurable {
    
    declare @type: ResearcherDataOnDemand: @Configurable;
    
}
