// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.ToolCatalogItem;
import au.net.huni.model.ToolCatalogItemDataOnDemand;
import au.net.huni.model.ToolCatalogItemIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ToolCatalogItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ToolCatalogItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ToolCatalogItemIntegrationTest: @Transactional;
    
    @Autowired
    ToolCatalogItemDataOnDemand ToolCatalogItemIntegrationTest.dod;
    
    @Test
    public void ToolCatalogItemIntegrationTest.testCountToolCatalogItems() {
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to initialize correctly", dod.getRandomToolCatalogItem());
        long count = ToolCatalogItem.countToolCatalogItems();
        Assert.assertTrue("Counter for 'ToolCatalogItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ToolCatalogItemIntegrationTest.testFindToolCatalogItem() {
        ToolCatalogItem obj = dod.getRandomToolCatalogItem();
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to provide an identifier", id);
        obj = ToolCatalogItem.findToolCatalogItem(id);
        Assert.assertNotNull("Find method for 'ToolCatalogItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ToolCatalogItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ToolCatalogItemIntegrationTest.testFindAllToolCatalogItems() {
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to initialize correctly", dod.getRandomToolCatalogItem());
        long count = ToolCatalogItem.countToolCatalogItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'ToolCatalogItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ToolCatalogItem> result = ToolCatalogItem.findAllToolCatalogItems();
        Assert.assertNotNull("Find all method for 'ToolCatalogItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ToolCatalogItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ToolCatalogItemIntegrationTest.testFindToolCatalogItemEntries() {
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to initialize correctly", dod.getRandomToolCatalogItem());
        long count = ToolCatalogItem.countToolCatalogItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ToolCatalogItem> result = ToolCatalogItem.findToolCatalogItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ToolCatalogItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ToolCatalogItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ToolCatalogItemIntegrationTest.testFlush() {
        ToolCatalogItem obj = dod.getRandomToolCatalogItem();
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to provide an identifier", id);
        obj = ToolCatalogItem.findToolCatalogItem(id);
        Assert.assertNotNull("Find method for 'ToolCatalogItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyToolCatalogItem(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ToolCatalogItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ToolCatalogItemIntegrationTest.testMergeUpdate() {
        ToolCatalogItem obj = dod.getRandomToolCatalogItem();
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to provide an identifier", id);
        obj = ToolCatalogItem.findToolCatalogItem(id);
        boolean modified =  dod.modifyToolCatalogItem(obj);
        Integer currentVersion = obj.getVersion();
        ToolCatalogItem merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ToolCatalogItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ToolCatalogItemIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to initialize correctly", dod.getRandomToolCatalogItem());
        ToolCatalogItem obj = dod.getNewTransientToolCatalogItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ToolCatalogItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ToolCatalogItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ToolCatalogItemIntegrationTest.testRemove() {
        ToolCatalogItem obj = dod.getRandomToolCatalogItem();
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ToolCatalogItem' failed to provide an identifier", id);
        obj = ToolCatalogItem.findToolCatalogItem(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ToolCatalogItem' with identifier '" + id + "'", ToolCatalogItem.findToolCatalogItem(id));
    }
    
}
