// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.net.huni.model;

import au.net.huni.model.ToolLibraryItem;
import au.net.huni.model.ToolLibraryItemDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ToolLibraryItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ToolLibraryItemDataOnDemand: @Component;
    
    private Random ToolLibraryItemDataOnDemand.rnd = new SecureRandom();
    
    private List<ToolLibraryItem> ToolLibraryItemDataOnDemand.data;
    
    public ToolLibraryItem ToolLibraryItemDataOnDemand.getNewTransientToolLibraryItem(int index) {
        ToolLibraryItem obj = new ToolLibraryItem();
        setDescription(obj, index);
        setName(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void ToolLibraryItemDataOnDemand.setDescription(ToolLibraryItem obj, int index) {
        String description = "_" + index;
        obj.setDescription(description);
    }
    
    public void ToolLibraryItemDataOnDemand.setName(ToolLibraryItem obj, int index) {
        String name = "name_" + index;
        if (name.length() > 64) {
            name = new Random().nextInt(10) + name.substring(1, 64);
        }
        obj.setName(name);
    }
    
    public ToolLibraryItem ToolLibraryItemDataOnDemand.getSpecificToolLibraryItem(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ToolLibraryItem obj = data.get(index);
        Long id = obj.getId();
        return ToolLibraryItem.findToolLibraryItem(id);
    }
    
    public ToolLibraryItem ToolLibraryItemDataOnDemand.getRandomToolLibraryItem() {
        init();
        ToolLibraryItem obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ToolLibraryItem.findToolLibraryItem(id);
    }
    
    public boolean ToolLibraryItemDataOnDemand.modifyToolLibraryItem(ToolLibraryItem obj) {
        return false;
    }
    
    public void ToolLibraryItemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ToolLibraryItem.findToolLibraryItemEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ToolLibraryItem' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ToolLibraryItem>();
        for (int i = 0; i < 10; i++) {
            ToolLibraryItem obj = getNewTransientToolLibraryItem(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
