INSERT INTO "APP"."FEEDBACK_ITEM" (ID,COMMENT,CONTEXT,RATING,VERSION,FEEDBACK_DATE,VISITOR_IP_ADDRESS) VALUES (1,'This is incredibly wonderful','/landing',3,0,{d '2013-08-12'},'');
INSERT INTO "APP"."FEEDBACK_ITEM" (ID,COMMENT,CONTEXT,RATING,VERSION,FEEDBACK_DATE,VISITOR_IP_ADDRESS) VALUES (3,'vcvcvcv','/landing',0,0,{d '2013-08-12'},'');
INSERT INTO "APP"."FEEDBACK_ITEM" (ID,COMMENT,CONTEXT,RATING,VERSION,FEEDBACK_DATE,VISITOR_IP_ADDRESS) VALUES (4,'uyuyuyuyu','/contact',2,0,{d '2013-08-12'},'');
INSERT INTO "APP"."FEEDBACK_ITEM" (ID,COMMENT,CONTEXT,RATING,VERSION,FEEDBACK_DATE,VISITOR_IP_ADDRESS) VALUES (5,'wqwqwqwqw','/advanced-search',4,0,{d '2013-08-12'},'');
INSERT INTO "APP"."FEEDBACK_ITEM" (ID,COMMENT,CONTEXT,RATING,VERSION,FEEDBACK_DATE,VISITOR_IP_ADDRESS) VALUES (6,'My comment','/about',1,0,{d '2013-08-08'},'127.0.0.1');
